version: '3.7'
services:
   ue:
    build:
      context: .
      args:
        vue_app_base_url: /mongo
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
    image: tms-mongodb-web/ue-mongo:latest
    container_name: mongo
    environment:
      - NGINX_WEB_BASE_URL=/mongo
